<?php

/**
 * @file
 * Home page.
 */

/**
 * Implements hook_menu().
 */
function home_menu() {

  $rows = array();

  $rows['home'] = array(
    'title' => 'Home',
    'page callback' => 'home_content',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dohome.inc'
  );

  $rows['more9'] = array(
    'title' => 'Home More',
    'page callback' => 'home_more9',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dohome.inc'
  );

  $rows['bot2020'] = array(
    'title' => t('World News'),
    'page callback' => 'bot2020',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'bot2020.inc'
  );

  /*
  $rows['more'] = array(
    'title' => 'Home More',
    'page callback' => 'home_more',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dohome.inc'
  );
   */

  $rows['nmore'] = array(
    'title' => 'Home More',
    'page callback' => 'home_nmore',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dohome.inc'
  );

  /*
  $rows['news'] = array(
    'title' => t('News'),
    'page callback' => 'home_news',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dohome.inc'
  );
   */

  $rows['news'] = array(
    'title' => t('News'),
    'page callback' => 'home_n',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dohome.inc'
  );

  return $rows;
}

/**
 * Implements hook_form_alter().
 * https://www.drupal.org/node/1291574
 */
function home_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_client_form_5364') { // Paste URL
    //$form['#validate'][] = 'home_validate_5364';

    $first = array_shift($form['#submit']);
    array_unshift($form['#submit'], $first, 'home_submit_5364');
  }
}

/**
 * Submit Paste URl form.
 */
function home_submit_5364(&$form, &$form_state) {
  $url = $form_state['input']['submitted']['url'];
 // dpm($url);
  if ($page = file_get_contents($url)) {  
    home_create_ding_yue_hao($page);
  }
  //dpm($page);
  dpm($matches[1][0]);
}

/**
 * Create a node of ding yue hao
 */
function home_create_ding_yue_hao($page) {
  preg_match('/var msg_cdn_url = \"([^\"]*)\"/', $page, $m_url, PREG_OFFSET_CAPTURE);
  preg_match('/var msg_title = \"([^\"]*)\"/', $page, $m_title, PREG_OFFSET_CAPTURE);
  preg_match('/var msg_desc = \"([^\"]*)\"/', $page, $m_desc, PREG_OFFSET_CAPTURE);

  $node = new stdClass();

  $node->title = $m_title[1][0];
  $node->uid = 1;
  $node->status = 1;
  $node->type = 'ding_yue_hao';
  $node->language = 'und';

  if ($file_url = $m_url[1][0]) {
    $file_tmp = file_get_contents($file_url);
    $file_name = 'abc.jpg';
    $file_tmp = file_save_data($file_tmp, 'public://gzh/' . $file_name, FILE_EXISTS_RENAME);
    $node->field_image = array(
      'und' => array(
        0 => array(
          'fid' => $file_tmp->fid,
          'filename' => $file_tmp->filename,
          'filemime' => $file_tmp->filemime,
          'uid' => 1,
          'uri' => $file_tmp->uri,
          'status' => 1,
          'display' => 1,
        )
      )
    );
  }

  node_save($node);

}

/**
 * Implements template_preprocess_page().
function home_preprocess_page(&$vars) {
  if (current_path() == 'home') {
    $vars['theme_hook_suggestions'][] = 'home_template';
  }
}
 */

/**
 * Implements hook_theme().
 */
function home_theme($existing, $type, $theme, $path) {

  $thePath = drupal_get_path('module', 'home') . '/templates';

  return array(
    /*
    'template_news' => array(
      'template' => 'news',
      'path' => $thePath,
    ),
     */
    'template_home' => array(
      'template' => 'home',
      'path' => $thePath,
    ),
  );
}


