<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function page_menu() {

  $rows = array();

  $rows['c/%'] = array(
    'title' => t('Articles'),
    'page callback' => 'page_c',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dopage.inc'
  );

  $rows['wechat_port'] = array(
    'title' => t('Articles'),
    'page callback' => 'page_wechat_port',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dopage.inc'
  );

  $rows['wechat_menu_config'] = array(
    'title' => t('Articles'),
    'page callback' => 'page_wechat_menu_config',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dopage.inc'
  );

  return $rows;
}

/**
 * Implements hook_preprocess_html().
 */
function page_preprocess_html(&$vars) {

  $arg0 = strtolower(trim(arg(0)));
  $arg1 = strtolower(trim(arg(1)));

  if ($arg0 === 'c') { // https://cn.muread.com/c/worldnews
    $termName = 'None';
    if ($arg1 === 'all') {
      $termName = '全部文章 | 必读';
    }

    $vars['head_title'] = $termName;
  }
}

/**
 * Implements hook_preprocess_page().
 */
function page_preprocess_page(&$vars) {

  $arg0 = strtolower(trim(arg(0)));
  $arg1 = strtolower(trim(arg(1)));

  if ($arg0 === 'c') { // https://cn.muread.com/c/worldnews
    $termName = 'None';
    if ($arg1 === 'all') {
      $termName = '全部文章';
    }

    $vars['term_name'] = $termName;
  }
}

/**
 * Implements hook_theme().
 */
function page_theme($existing, $type, $theme, $path) {

  $thePath = drupal_get_path('module', 'page') . '/templates';

  return array(
    'template_c_all' => array(
      'template' => 'c_all',
      'path' => $thePath,
    ),
  );
}


