<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function page_menu() {

  $rows = array();

  $rows['c/%'] = array(
    'title' => t('Articles'),
    'page callback' => 'page_c',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dopage.inc'
  );

  $rows['more'] = array(
    'title' => 'More',
    'page callback' => 'page_more',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dopage.inc'
  );

  $rows['wechat_port'] = array(
    'title' => t('Articles'),
    'page callback' => 'page_wechat_port',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dopage.inc'
  );

  $rows['wechat_menu_config'] = array(
    'title' => t('Articles'),
    'page callback' => 'page_wechat_menu_config',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'dopage.inc'
  );

  $rows['p'] = array(
    'title' => '发布',
    'page callback' => 'page_paste',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'url_paste.inc'
  );

  return $rows;
}

/**
 * Implements hook_form_alter().
 * https://www.drupal.org/node/1291574
 */
function page_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'webform_client_form_5364') { // Paste URL
    //$form['#validate'][] = 'home_validate_5364';

    $first = array_shift($form['#submit']);
    array_unshift($form['#submit'], $first, 'page_submit_5364');
  }
}

/**
 * Submit Paste URl form.
 */
function page_submit_5364(&$form, &$form_state) {
  $url = $form_state['input']['submitted']['url'];
  $categories = $form_state['input']['submitted']['categories'];
  if ($page = file_get_contents($url)) {
    page_create_ding_yue_hao($page, $url, $categories);
  }
}

/**
 * Implements hook_preprocess_html().
 */
function page_preprocess_html(&$vars) {

  $arg0 = strtolower(trim(arg(0)));
  $arg1 = strtolower(trim(arg(1)));

  if ($arg0 === 'c') { // https://cn.muread.com/c/worldnews
    $termName = 'None';
    if ($arg1 === 'all') {
      $termName = '全部文章 | 必读';
    }
    else {
      $termInfo = page_get_term_info($arg1); 
      $termName = $termInfo['name'] . ' | 必读';
    }

    $vars['head_title'] = $termName;
  }
  else if ($arg0 == 'home') {
    $vars['head_title'] = '必读';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function page_preprocess_page(&$vars) {

  $arg0 = strtolower(trim(arg(0)));
  $arg1 = strtolower(trim(arg(1)));

  if ($arg0 === 'c') { // https://cn.muread.com/c/worldnews
    $termName = 'None';
    if ($arg1 === 'all') {
      $termName = '全部文章';
    }
    else {
      $termInfo = page_get_term_info($arg1); 
      $termName = $termInfo['name'];
    }
    $vars['term_name'] = $termName;
  }
  else if ($arg0 == 'node' && is_numeric($arg1)) {
    $node = node_load($arg1);
    if ($node->type == 'ding_yue_hao') {
      $vars['theme_hook_suggestions'][] = 'page_ding_yue_hao';

      $page_path = drupal_get_path("module", "page");
      drupal_add_css($page_path . '/css/page_ding_yue_hao.css');
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function page_preprocess_node(&$node) {
  if ($node['type'] == 'ding_yue_hao') {
    $node['theme_hook_suggestions'][] = 'node_ding_yue_hao';

    $node['published'] = '';
    if (!empty($node['field_published_date'])) {
      $node['published'] = date('Y-m-d', $node['field_published_date'][0]['value']);
    }

    $node['author'] = '';
    if (!empty($node['field_author'])) {
      $node['author'] = $node['field_author'][0]['value'];
    }
  }
}

/**
 * Implements hook_theme().
 */
function page_theme($existing, $type, $theme, $path) {

  $thePath = drupal_get_path('module', 'page') . '/templates';

  return array(
    'template_c_all' => array(
      'template' => 'c_all',
      'path' => $thePath,
    ),
    'page_ding_yue_hao' => array(
      'template' => 'page_ding_yue_hao',
      'path' => $thePath,
    ),
    'node_ding_yue_hao' => array(
      'template' => 'node_ding_yue_hao',
      'path' => $thePath,
    ),
    'template_paste' => array(
      'template' => 'paste',
      'path' => $thePath,
    ),
  );
}


